apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-2bbv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-2bbv
    app.kubernetes.io/part-of: tkrw-pr714-0075-0050-app
  name: devfile-sample-2bbv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-2bbv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-2bbv
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0050-tenant/tkrw-pr714-0075-0050-app/devfile-sample-2bbv@sha256:cb2217449dee0b743fa0693468c1bd22195e93000b6264635ea7570ad7236c87
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
